### ISSUE TITLE
Expose booking state and add booking history

### ISSUE THREAD

**Issue by stakach** [PlaceOS/staff-api#143]
A new addition to the Booking controller / Booking model

* `current_state` (inferred on render, not stored in the db)
   * reserved, checked-in, checked-out, no-show, rejected, canceled, ended
* allow a source of event param (mobile, desktop, kiosk etc) `?utm_source=`
* a history of state changes where `source` is obtained from `utm_source`

```
history: [{
  state: "reserved",
  time: 12345,
  source: "mobile"
},
{
  state: "checked-in",
  time: 12346,
  source: "floorsense"
}]
```

where the current states are:

* `reserved`: booking starts in the future, no one has checked-in and it hasn't been deleted
* `checked-in`: booking is currently active (the wall clock time is between start and end times of the booking) and the user has checked in
* `checked-out`: the user checked out during the start and end times
* `no-show`: it's past the end time of the booking and it was never checked in
* `rejected`: someone rejected the booking before it started
* `canceled`: the booking was deleted before the booking start time
* `ended`: the current time is past the end of the booking, the user checked-in however never checked-out

I think adding a [JSON column](https://github.com/PlaceOS/staff-api/blob/master/src/models/booking.cr#L53) for `history` is probably the simplest solution

**Comment by chillfox** [comment]
There is a `booked_from` column that could be used instead of adding `utm_source`
```cr
  # if we want to record the system that performed the bookings
  # (kiosk, mobile, swipe etc)
  column booked_from : String?
```

**Comment by stakach** [comment]
Thanks for pointing that out!
Can we set that field manually if it's currently `nil` and `?utm_source=` is provided

as that field is only meant to be used on creation really, whereas we'll use the `utm_source` param to fill in the history for every action the user takes

i.e. they created on a laptop, edited on a mobile phone and then the booking was auto-checked out by floorsense

**Comment by stakach** [comment]
A few additional cases need to be taken into account when generating history:
https://github.com/place-technology/suncorp-ntt/issues/173#issuecomment-1034841686

1. When current_time > booking_start the booking is returning `unknown` - should be `reserved`, and then `no-show` once current_time > booking_end
2. A deleted booking where deleted_at > booking_start is returning `unknown`. Should be `no-show`
3. if user checks-in to booking prior to start time, history does not capture the check-in state and state should be `checked-in` - currently returns `unknown`
4. it is also possible that user checks-in and checks-out prior to start of the booking - it should record the state history and return `cancelled` (check-out before start time == cancelled)
