### ISSUE TITLE
Handling of various directory user/mailbox cases 

### ISSUE THREAD

**Issue by w-le** [PlaceOS/staff-api#158]
We can meet about this to discuss. IMO the goals are:
1. Allow workplace apps to query and create room bookings for Azure AD GUEST users (they [have mailboxes](https://azure.microsoft.com/en-us/pricing/details/active-directory/external-identities/) you know), by changing our MS Graph API user identification parameter from email address (does not work with guests and will not work when the company sets staff UserPrincipalName to a value that is not the email address) to MS Graph `id` aka GUID (works for all users). 

2. Improve API responses for various user/mailbox state cases such that frontend can display different UI elements based on what Directory options are available for the current user (only show room booking options if the user HAS a mailbox)

Facts that have lead to the current behaviour (unable to book events as an Azure AD Guest even though Azure AD guests have mailboxes)
1. PlaceOS currently utilises user's EMAILs as the primary identifier for the directory user
2. MS Graph expects users to be identified via ms graph `id` or `UserPrincipalName`
3. The only reason that (1) works is because most (not all) enterprises set staff user UPNs to be the email. This may easily not be the case for some future client
4. AD Guest object UPNs are different, and are in the format `name_originaldomain#EXT#@domain.com` See https://stackoverflow.com/questions/46951238/get-a-guest-user-by-userprincipalname-with-microsoft-graph
5. Thus when placeos tries to query the guest user with just their email address, it's a 404 from Graph, even though it could easily be a 200 if we changed our query.
6. Once we start geting the Guest users corectly, we'll be able to start searching and creating events as them, because by default AD Guests have mailboxes!

More detailed cases that we should address:
When a PlaceOS user logs into a workplace app, it will generally attempt to GET that user's staff-api a) `/people/id` and b) `/calendars`
Here are the different cases that could occur, their current api response and a suggested better api response:

1. The user exists in the directory and has an active mailbox
 a. 200
 b. 200
2. The user exists in the directory and does not have an active mailbox
 a. 200
 b. 500 (404 would be better)
3. The user exists in the directory as a guest and has an active mailbox
 a. 500 (we can make this 200)
 b. 500 (we can make this 200)
4. The user exists in the directory as a guest and does not have an active mailbox
 a. 500 (we can make this 200)
 b. 500 (404 would be better)
5. The user does not exist in the directory
 a. 500 (we should make this 404)
 b. 500 (when frontends gets 404 for a it should not attempt b and not show UI options for Room searching/booking)

**Comment by jeremyw24** [comment]
@stakach  advised complete
