### ISSUE TITLE
Update how we validate bookings

### ISSUE THREAD

**Issue by stakach** [PlaceOS/staff-api#165]
currently we have the following fields
* booking_start
* booking_end
* checked_out_at

However we only consider the start and end times when interacting with bookings.
We want to make a change that considers `checked_out_at` as the true booking end time (without changing booking_end)

So you can think of `checked_out_at` as an override for `booking_end` for any of our logic.

That means:
* new bookings can be made before `booking_end` if `checked_out_at` is set (no clash)
* if someone wants to check-back-into a booking, need to check for clashes before allowing it (as a newly created booking might be preventing it)
* by default we don't want to return any bookings that have `checked_out_at` set (the api should return active bookings)
* we need a new flag that will include the `checked_out_at` bookings

https://github.com/place-technology/suncorp-ntt/issues/204

**Comment by vik-pfqld** [comment]
at the moment people are able to check-in and check-out of the booking multiple times.  also if they re-check-in then do we then overwrite the check-in time? this will result in checked_in_at > checked_out_at

do we have a definitive list of what will be allowed by API and what will not be?
e.g.
1. check-in before the booking starts (requires checking that the resource is available, perhaps should be restricted to certain duration before the booking start?)
2. check-in after the booking is finished (should this be allowed?)

**Comment by stakach** [comment]
1. check-in before the booking starts requires checking that the resource is available and we can probably allow it as long as it's the same date in the users timezone i.e. booked for 8am on the 6th then you can check in anytime before that as long as it's the 6th
2. probably shouldn't be allowed
