### ISSUE TITLE
Regression Test Delegated Permissions

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/staff-api#184]
- [x] Regression Test https://placeos-dev.aca.im/staff/

- [ ] Regression Test https://placeos-dev.aca.im/conciege/

- [ ] Regression Test https://placeos-dev.aca.im/kiosk/

- [ ] Regression Test https://placeos-dev.aca.im/enrolment/

- [ ] Regression Test https://placeos-dev.aca.im/catering/

**Comment by w-le** [comment]
blocked by #181
