### ISSUE TITLE
Allow PUT Event Metadata such that fields like people_count can be recorded for every event (by a logic module in that room)

### ISSUE THREAD

**Issue by w-le** [PlaceOS/staff-api#206]
Allow PUT Event Metadata such that fields like people_count can be recorded for every event (by a logic module in that room, as the event is occurring in the room).

As discussed with Steve, Will, Alex.
This will allow a much easier alternative to Concierge reports page querying Influx directly and having to collate data between staff-api and influx.

Bonus: record min, max, avg people counts for every Event.
Maybe something like:
```
event.ext_data.people_count: {
  min: 2
  max: 3
  avg: 2.86
}
```

Primary Goal:
- Frontend apps querying events in a date range, should receive people count data if it's been added to event metadata (by a logic driver, during event start-end time)

**Comment by w-le** [comment]
Wait if Events already have ext_data field, and that's free form JSON. Doesn't that mean no staff-api change is neccessary? Only the Logic Driver to do the PUTs need to be written?

Another question? is Event.ext_data the same as Event Metadata?

**Comment by stakach** [comment]
Yeah we just need to update the driver to use the existing APIs
`Event.extension_data` is `EventMetadata.ext_data`

The internal representations are different to what is sent down the API

**Comment by w-le** [comment]
1. "update the driver to use the existing APIs" update which driver? I thought It's a brand NEW logic driver to be written? So that mean no staff-api change is necessary right? Do confirm and I'll close this issue.

2. It sounds like the **ONLY** dev work required is to write a NEW Logic Driver that will PUT people counts to event metadata as events are occurring. Is that correct? Or is there some other backend work also required that I've missed?

3. So that means when Concierge app queries all events in Systems/Zones in a date range, the current response already has event.ext_data (which will include the people counts after we finish 2) - right? So frontend wont even need to change the GET Request it makes.

**Comment by w-le** [comment]
closed for https://github.com/place-labs/google-staff-api/issues/21
