### ISSUE TITLE
Some currently existing issues in staff-api src

### ISSUE THREAD

**Issue by dukeraphaelng** [PlaceOS/staff-api#80]
It'd be quite annoying to open each issue for each of these dot points, so instead of doing so, I've created this issue which is comprised of all of the problems which I have found currently with staff-api.

For each dot point, only one reference example is included, please fix all other existing similar problems

## Style

- [x] Prefer `unless` over `if !(expression)`, [example](https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/tenants.cr#L20)

Ameba did not run here probably due to it not going into the deeper macro context

## Refactor

- [x] Store ENVS as constants in a single [file](https://github.com/place-labs/staff-api/blob/master/src/constants.cr), example: [1](https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/utilities/google-helpers.cr#L6-L12)

## Security

- [x] ~User var() for query sanitisation like [here](https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/guest.cr#L35) instead of [this](https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/tenant.cr#L100)~

## Optimisation

- [x] User find_or_create instead of [this](https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/tenant.cr#L89-L97)

### Mass Assignment

Prevent mass assignment of fields like `id`, and implement direct deserialisation, i.e. `create_from_json`

**examples**

  For this example, I'm not sure why we are serialising credentials here though
  
- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/bookings.cr#L114-L115

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/tenants.cr#L11-L18

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/guests.cr#L180-L188

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/guests.cr#L145-L169

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/bookings.cr#L53-L54

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/bookings.cr#L78

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/bookings.cr#L114-L138

### Double serialisation

**examples**

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/guests.cr#L168

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/controllers/utilities/responders.cr#L5-L25

- [x] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/booking.cr#L151-L159

### `#as_json` for selective serialisation

Implement #as_json or expand [Clear JSONDeserialise model to accept annotation as macro arg in 

- [ ] Clear](https://github.com/place-labs/clear/issues/7)

**examples** 

- [ ] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/tenant.cr#L67-L74

- [ ] https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/booking.cr#L151-L159

- [ ] Implement #as_json for [1](https://github.com/place-labs/staff-api/blob/c099e3befe407b8a2c6c8a3958d704706c19fa4b/src/models/guest.cr#L42-L64), [2](https://github.com/place-labs/staff-api/blob/master/src/models/attendee.cr#L22-L34)

**Comment by tassja** [comment]
All points addressed except for `as_json` implementation which has been extracted into its own issue
https://github.com/PlaceOS/staff-api/issues/154
